### ISSUE TITLE
out of bounds read in mz_zip_reader_read_central_dir

### ISSUE THREAD

**Issue by khang06** [richgel999/miniz#95]
using a modified version @Sumerian123's test harness, i found this bug using afl
[testcase.zip](https://github.com/richgel999/miniz/files/2153343/testcase.zip)
ASAN output:
```
==10360==ERROR: AddressSanitizer: SEGV on unknown address 0x610000017f66 (pc 0x000000523092 bp 0x7fffdb8aac00 sp 0x7fffdb8a8920 T0)
==10360==The signal is caused by a READ memory access.
    #0 0x523091 in mz_zip_reader_read_central_dir /home/khangaroo/github/miniz/amalgamation/miniz.c:3661:43
    #1 0x520ef3 in mz_zip_reader_init /home/khangaroo/github/miniz/amalgamation/miniz.c:3783:10
    #2 0x503a51 in test_func(char*) /home/khangaroo/github/miniz/miniz_test_harness.cpp:62:12
    #3 0x503f3c in main /home/khangaroo/github/miniz/miniz_test_harness.cpp:143:3
    #4 0x7f6fdc23f1c0 in __libc_start_main /build/glibc-itYbWN/glibc-2.26/csu/../csu/libc-start.c:308
    #5 0x41bdc9 in _start (/home/khangaroo/github/miniz/miniz+0x41bdc9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/khangaroo/github/miniz/amalgamation/miniz.c:3661:43 in mz_zip_reader_read_central_dir
==10360==ABORTING
```
the crash appears to happen in this line:
`field_data_size = MZ_READ_LE16(pExtra_data + sizeof(mz_uint16));`

**Comment by uroni** [comment]
Thanks for testing and for the detailed bug report!

Should be fixed with 9ce0d0ddffaf9f69625865e68d44f25b54484ed6
